services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped