name: flights
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - alembic==1.14.1
      - click==8.1.8
      - dnspython==2.7.0
      - email-validator==1.0.5
      - Flask==3.1.0
      - Flask-Cors==5.0.0
      - Flask-Migrate==4.1.0
      - Flask-SQLAlchemy==3.1.1
      - Flask-Validator==1.4.1
      - greenlet==3.1.1
      - iniconfig==2.0.0
      - isbnlib==3.9.10
      - iso3166==1.0.1
      - itsdangerous==2.2.0
      - Jinja2==3.1.5
      - Mako==1.3.9
      - MarkupSafe==3.0.2
      - psycopg2-binary==2.9.10
      - py-moneyed==0.8.0
      - PyJWT==2.10.1
      - pytest==8.3.4
      - pytest-cov==6.0.0
      - pytest-flask==1.3.0
      - pytz==2019.3
      - schwifty==2020.2.2
      - setuptools
      - SQLAlchemy==2.0.37
      - typing_extensions==4.12.2
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - zstandard==0.23.0
      - coverage>=7.5
      - requests==2.26.0