name: flights
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - alembic==1.15.1
      - click==8.1.8
      - dnspython==2.7.0
      - email-validator==2.2.0
      - Flask==3.1.0
      - Flask-Cors==5.1.0
      - Flask-Migrate==4.1.0
      - Flask-SQLAlchemy==3.1.1
      - Flask-Validator==1.4.2
      - greenlet==3.1.1
      - iniconfig==2.1.0
      - isbnlib==3.10.14
      - iso3166==2.1.1
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - Mako==1.3.9
      - MarkupSafe==3.0.2
      - psycopg2-binary==2.9.10
      - py-moneyed==3.0
      - PyJWT==2.10.1
      - pytest==8.3.5
      - pytest-flask==1.3.0
      - pytz==2025.2
      - schwifty==2025.1.0
      - setuptools==78.1.0
      - SQLAlchemy==2.0.39
      - typing_extensions==4.13.0
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - zstandard==0.23.0
      - coverage==7.7.1
      - requests==2.26.0
